### ISSUE TITLE
Berekening

### ISSUE THREAD

**Issue by stafra00** [Laoujin/ttc-test-tabtapi#1]
Hoi, 
Hoe kan je het klassement berekenen (Limburg-Kempen, Vlaams Brabant, Residu) met behulp van deze module?

**Comment by Laoujin** [comment]
Dit is enkel een formulier om de API van Frenoy aan te spreken.

De verschillende berekeningen zijn hier beschreven:
http://tabt.frenoy.net/index.php?l=NL&display=TabTWebDocNewClass_NL

Er zijn andere projecten:
https://github.com/Timvissers/tafeltennis-klassementen-be

Er was er ook eentje dat heel nauwkeurig was met AI maar ik vind de source niet terug
